<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery-1.12.4.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/GSAP/TweenMax.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/GSAP/plugins/ScrollToPlugin.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.fitvids-1.1.0.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.unveil.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/slick.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/ScrollMagic/ScrollMagic.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/ScrollMagic/animation.gsap.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/bentmetalblog.main.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/bentmetalblog.blog-single.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/bentmetalblog.blog.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/bentmetalblog.gallery.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/bentmetalblog.search-results.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/bentmetalblog.search.js"></script>
